version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bookreviews
      POSTGRES_USER: utkrusht_user
      POSTGRES_PASSWORD: securepass123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - reviewnet
  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://utkrusht_user:securepass123@db:5432/bookreviews
    ports:
      - '8000:8000'
    volumes:
      - ./:/code
    networks:
      - reviewnet
volumes:
  pgdata:
networks:
  reviewnet:
